### ISSUE TITLE
hhvm support checklist

### ISSUE THREAD

**Issue by rahul286** [rtCamp/easyengine#199]
Related to #180 

- [ ] Analyze https://github.com/facebook/hhvm/search?q=wordpress&type=Issues
- [ ] test wp-cli
- [ ] what happens to php5-fpm (max children reached monitoring etc)
- [ ] does xdebug works nicely?
- [ ] what about zend-opcache?
- [ ] Analyze upstart script - http://community.rtcamp.com/t/hhvm-upstart-script/3450/7

**Comment by harshadyeola** [comment]
Please update your EasyEngine versions to its latest, to use HHVM support.
Ya it's released :)
